### ISSUE TITLE
Restful API Documentation

### ISSUE THREAD

**Issue by MarkusSe** [tanmoythander/node-rest-server#1]
Hi,

is there a documentation about the offered API. 
I tried to use it and the server seems to start perfectly including connection to the database.
But any RestFul Request that I try to send is rejected with a "Not Found" 404

**Comment by tanmoythander** [comment]
Hello, the REST API documentation can be found at https://api.tanmoythander.info/node-rest-server/
Please don't forget to clone the latest release. :)
